pull_request_rules:
  - name: branch name check
    conditions:
      - "head~=^(master|main)/"
      - "-merged"
      - "-closed"
    actions:
      close:
        message: |
          @{{author}}
          Wrong Branch Name: {{head}}
          Please use a meaningful name instead.
          This Pull Request will be closed.
      label:
        add:
          - "invalid"
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=test
    actions:
      merge:
        method: rebase
  - name: automatic approve for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=test
      - "-conflict"
      - "-closed"
    actions:
      review:
        type: APPROVE
        message: |
          Mergify Automatic Approve Successful Renovate PR
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=test
    actions:
      merge:
        method: rebase
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: automatic label Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      label:
        add:
          - "dependency"
          - "bot"
  - name: automatic label Renovate pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      label:
        add:
          - "bot"
